name: cppcheck-action

on: [push]

jobs:
  build:
    name: cppcheck-test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: cppcheck
        run: sudo ./svc.sh stop && sudo ./svc.sh start
        uses: deep5050/cppcheck-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          output_file : ./cppReports/cppReport (Run ${{ github.run_number }}) - ${{ github.actor }}
          enable: warning,performance,portability

      - name: publish report
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: 'main'