name: Doxygen Action

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Doxygen Action
        uses: mattnotmitt/doxygen-action@v1.1.0
        with:
          # Path to Doxyfile
          doxyfile-path: "./Doxyfile" # default is ./Doxyfile
          # Working directory
          working-directory: "." # default is .